Update ptrace.h: include <asm/ptrace.h> for powerpc
This fixes compilation error, which was found while using musl for powerpc:

In file included from attach.c:43:0:
ptrace.h:69:20: error: field 'regs' has incomplete type
     struct pt_regs regs;
                    ^~~~
<builtin>: recipe for target 'attach.o' failed